# Generated by Django 2.2.3 on 2019-07-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=11)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('pass_code', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title1', max_length=50)),
                ('video_name', models.CharField(max_length=60)),
                ('path', models.FileField(blank=True, upload_to='video')),
                ('duration', models.CharField(default='00:00:00', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='WordInfo',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.UserBase')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleInfo',
            fields=[
                ('subtitle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('path', models.FileField(upload_to='srt')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.VideoInfo')),
            ],
        ),
        migrations.CreateModel(
            name='NoteInfo',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sentence', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='voice')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.VideoInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlFilePersian',
            fields=[
                ('htmlfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('path', models.FileField(upload_to='htmlpersian')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.VideoInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlFileInfo',
            fields=[
                ('htmlfile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('path', models.FileField(upload_to='html')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.VideoInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('repetition', models.IntegerField(blank=True, default=0)),
                ('interval', models.IntegerField(blank=True, default=0)),
                ('efactor', models.FloatField(blank=True, default=2.5)),
                ('nextpracticedate', models.DateField(default='2019-07-31')),
                ('create_date', models.DateField(default='2019-07-30')),
                ('types', models.CharField(default='word', max_length=60)),
                ('note_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapi.NoteInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.UserBase')),
                ('word_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapi.WordInfo')),
            ],
        ),
    ]
