# Generated by Django 2.2.3 on 2019-07-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='create_date',
            field=models.DateField(default='2019-07-31'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='nextpracticedate',
            field=models.DateField(default='2019-08-01'),
        ),
    ]
